In [2]:
import open3d as o3d
import numpy as np

# Example for reading point cloud
Load below cell to read point cloud!

In [3]:
# I open point cloud file called Full_Point_Cloud.ply
# This is the original file from SAIE Lab
# Trying to crop it!
cloud = o3d.io.read_point_cloud("Full_Point_Cloud.ply")
# tell us about this file!
print(cloud)

PointCloud with 56569957 points.


# Example for writing point cloud

In [ ]:
# I copy the contents of Full_Point_Cloud.ply to a new file called Part_1.ply
o3d.io.write_point_cloud("Part_1.ply", cloud)
# I read Part_1.ply
p1 = o3d.io.read_point_cloud("Part_1.ply")
print(p1)

# Notes about the point cloud
W.r.t the .TIFF file, the .PLY file is rotated about 30 degrees

# Crop Method 1: (good method so far)
>part1 = p1_crop_(0,-30,0).ply
><br>part2 = p1_crop_(-200,-130,0).ply
><br>part3 = p1_crop_(300,-50,0).ply
# Mesh output: (week 3, Jan 30 ~ Feb 5, 2023)
Software: Meshlab
>part1 = part1_Mesh.ply
><br>part2 = part2_Mesh.ply (normals are flipped w.r.t. view)
><br>part3 = part3_Mesh.ply (normals are flipped w.r.t. view)

<br>Note: using 'flip normals w.r.t. view' option in normal calculation results in Bad (self-intersecting & Not abiding to point cloud) poisson mesh!
><br>230216 update: For 'flipped normal' point clouds, I reconstruct meshes, and then force-flip their normals.
# Findings:
It's Faster to 'navigate' the mesh using Crop Method 1, because if I open the entire point cloud in Meshlab, the software slows down so much I canNot do operations (e.g. cropping) quickly because of lag

## My reference mesh is:
Part1_Mesh.ply
<br><img src="../ReferenceImages/ReferenceImage2230211.png" style="width: 400px">
<br>Mesh from 230209. scale=150, poisson path=8
With these settings, we see contour-like (in yellow) lines at the lower half. 
<br>Along these lines, the wireframe is dense
We need to find out if these are features

# Logs:
### 230209
Today I need crop out Smaller parts from p1_crop_(0,-30,0).ply
We noticed that K1 curvature option (from Meshlab's colorization) colorize the mesh in a way most helpful for identifying features
<br>Size: 24
### 230211
<br>Today I crop out a small part and a bigger part on the contour-line-like structure
<br>Reference for location: Part1_Mesh.ply, centered at (0, -30, 0)
<br>Small square vtx count: 100k
<br>Large square vtx count: 200k
### 230212
Today I make three changes:
<br>1) even smaller crop sizes <- 1/2 of smallest scale from yesterday
<br>2) put images of the same category on Same row <- pictures at different scales on same row
<br>3) add region with Actual archaeological features
### 230213
Cropped out areas 3 and 4, recorded Exaggerated Shading
For Crest Lines, I tried all files, but it seems only ones with size less than 2.5mb could be loaded (without the .exe file freezing)
### 230215 (TODO)
In today's meeting, we found that when the archaeological feature is big, zooming in (reducing crop size a lot) does not help us identify features.
<br>1) 2 regions of same size from ea (of 3 base mesh), plus 2 circled out today, SAME crop size
<br>2) color (Meshlab curvature), change scale (1st parameter of APSS curvature)
<br>3) find common scale where features show up (only archaeological feature, no noise)
### 230216
Added mesh colorization for Areas 5, 6, 7, 8, 9, 10, and 11.
<br>I fixed the size of the crop, and varied the 'MLS scaling' field in increasing steps of 2 from 2 (default value) to 14.
<br>I also increased the size of the crops to scale=24, since in a smaller scale, I cannot always capture the entirety of some features across different areas of interest
>Area 5, 6, 7 come from Part1_Mesh.
><br>Area 8, 9 come from Part2_Mesh.
><br>Area 10, 11 come from Part3_Mesh.



# **Part 1 Meshes:** 
Center: (0, -30, 0)
File: part1_Mesh.ply
<br><img src="../ReferenceImages/ReferenceImage2230211.png" style="width: 400px">
<br>Mesh from 230209. scale=150, poisson path=8
<br>With these settings, we see contour-like (in yellow) lines at the lower half. 
<br>Along these lines, the wireframe is dense
We need to find out if these are features

# Area 1, center = (0, -64, 0)
*On 230209, we noticed some contour lines in this region. We zoom in to see if it is grid-dependent (i.e. if it is the result of the surface reconstruction, rather than the result of there actually being contour-like structures)*

Here's Area 1 (largest scale) on the the reference mesh: 230211_size=24_01.ply
<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_01_max-size.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_01_top.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_01_rot_ortho.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_01_rot_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">scale = 6</td>
    <td style = "text_aligh:left">scale = 12</td>
    <td style = "text_aligh:left">scale = 18</td>
    <td style = "text_aligh:left">scale = 24</td>
</tr>
<tr>
    <td style = "text_aligh:left">22572 points</td>
    <td style = "text_aligh:left">89868 points</td>
    <td style = "text_aligh:left">199530 points</td>
    <td style = "text_aligh:left">352161 points</td>
</tr>
<tr>
    <td style = "text_aligh:left">miniCrop_(0,-64,0)_scale=6.ply</td>
    <td style = "text_aligh:left">miniCrop_(0,-64,0)_scale=12.ply</td>
    <td style = "text_aligh:left">miniCrop_(0,-64,0)_scale=18.ply</td>
    <td style = "text_aligh:left">miniCrop_(0,-64,0)_scale=24.ply</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/230212_size=6_01_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Screen%20Shot%202023-02-11%20at%207.33.51%20PM.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Screen%20Shot%202023-02-11%20at%207.34.18%20PM.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Screen%20Shot%202023-02-11%20at%207.44.33%20PM.png"/></td>
</table>

Exaggerated Shading for scale = 6

<table>
<tr>
    <td style = "text_aligh:left">relief</td>
    <td style = "text_aligh:left">ridges</td>
    <td style = "text_aligh:left">shading</td>
    <td style = "text_aligh:left">valleys</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230212/230212_size=6_01_reliefs.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230212_size=6_01_ridges.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230212_size=6_01_shading.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230212_size=6_01_valleys.PNG"/></td>
</tr>
</table>

Exaggerated Shading for scale = 12

<table>
<tr>
    <td style = "text_aligh:left">relief</td>
    <td style = "text_aligh:left">ridges</td>
    <td style = "text_aligh:left">shading</td>
    <td style = "text_aligh:left">valleys</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230212/230211_size=12_01_reliefs.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=12_01_ridges.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=12_01_shading.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=12_01_valleys.PNG"/></td>
</tr>
</table>

# Area 1 Conclusion:
The contour-like structures are probably grid-based artefacts!

# Area 2, center = (-10, 10, 0)
*We also noticed some contour-like structures in this area, so I repeat the process to verify*

Here's Area 2 (largest scale) on the the reference mesh: 230211_size=16_02.ply <- Note: scale is actually 16!
*The circular/bubbly 'skirt' part around the square edge of the mesh of interest is the result of screened poisson mesh reconstruction. The point cloud used for reconstruction is a square when viewed from the top!*
<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_02_max-size.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_02_top.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_02_rot_ortho.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_02_rot_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">scale = 5</td>
    <td style = "text_aligh:left">scale = 10</td>
    <td style = "text_aligh:left">scale = 12</td>
    <td style = "text_aligh:left">scale = 16</td>
</tr>
<tr>
    <td style = "text_aligh:left">35165 points</td>
    <td style = "text_aligh:left">199530 points</td>
    <td style = "text_aligh:left">233659 points</td>
    <td style = "text_aligh:left">453444 points</td>
</tr>
<tr>
    <td style = "text_aligh:left">miniCrop_(-10,10,0)_scale=5.ply</td>
    <td style = "text_aligh:left">miniCrop_(-10,10,0)_scale=10.ply</td>
    <td style = "text_aligh:left">miniCrop_(-10,10,0)_scale=12.ply</td>
    <td style = "text_aligh:left">miniCrop_(-10,10,0)_scale=16.ply</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/230212_size=5_02_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Screen%20Shot%202023-02-11%20at%208.01.03%20PM.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Screen%20Shot%202023-02-11%20at%208.04.35%20PM.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Screen%20Shot%202023-02-11%20at%208.08.38%20PM.png"/></td>
</table>

Exaggerated Shading for scale = 5

<table>
<tr>
    <td style = "text_aligh:left">relief</td>
    <td style = "text_aligh:left">ridges</td>
    <td style = "text_aligh:left">shading</td>
    <td style = "text_aligh:left">valleys</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230212/230212_size=5_02_reliefs.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230212_size=5_02_ridges.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230212_size=5_02_shading.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230212_size=5_02_valleys.PNG"/></td>
</tr>
</table>

Exaggerated Shading for scale = 10

<table>
<tr>
    <td style = "text_aligh:left">relief</td>
    <td style = "text_aligh:left">ridges</td>
    <td style = "text_aligh:left">shading</td>
    <td style = "text_aligh:left">valleys</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230212/230211_size=10_02_relief.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=10_02_ridges.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=10_02_shading.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=10_02_valleys.PNG"/></td>
</tr>
</table>

Crest Lines for scale = 10
(the three coordinates refer to the rough position of the three parameters for crest line display, top to bottom)
<table>
<tr>
    <td style = "text_aligh:left">default setting</td>
    <td style = "text_aligh:left">0.25, 0.5, 0</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230212/230211_size=10_02_curves_default.PNG"/></td>
    <td style="width: 240px;"><img src="../230212/230211_size=10_02_curves_(.25,.5,0).PNG"/></td>
</tr>
</table>

Crest Lines for scale = 16
(the three coordinates refer to the rough position of the three parameters for crest line display, top to bottom)
<table>
<tr>
    <td style = "text_aligh:left">default setting</td>
    <td style = "text_aligh:left">0.25, 0.5, 0</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230213/230213_size=16_02_curves_default.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230213_size=16_02_curves_(.25,.5,0).PNG"/></td>
</tr>
</table>
It seems that there are some contour-like patterns. Even in plain shading, I can see them as bumps.

# Area 3, center = (0, -30, 0)
This is an area with archeological features

Here's Area 3 (largest scale) on the the reference mesh: 230213_size=18_03.ply 
<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_03_max-size.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_03_top.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_03_rot_ortho.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_03_rot_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">scale = 6</td>
    <td style = "text_aligh:left">scale = 9</td>
    <td style = "text_aligh:left">scale = 12</td>
    <td style = "text_aligh:left">scale = 18</td>
</tr>
<tr>
    <td style = "text_aligh:left">48005 points</td>
    <td style = "text_aligh:left">107127 points</td>
    <td style = "text_aligh:left">191436 points</td>
    <td style = "text_aligh:left">436758 points</td>
</tr>
<tr>
    <td style = "text_aligh:left">miniCrop_(0,-30,0)_scale=6.ply</td>
    <td style = "text_aligh:left">miniCrop_(0,-30,0)_scale=9.ply</td>
    <td style = "text_aligh:left">miniCrop_(0,-30,0)_scale=12.ply</td>
    <td style = "text_aligh:left">miniCrop_(0,-30,0)_scale=18.ply</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=6_03_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=9_03_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=12_03_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=18_03_K1.png"/></td>
</table>

Exaggerated Shading for scale = 6

<table>
<tr>
    <td style = "text_aligh:left">relief</td>
    <td style = "text_aligh:left">ridges</td>
    <td style = "text_aligh:left">shading</td>
    <td style = "text_aligh:left">valleys</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230213/230211_size=6_03_reliefs.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230211_size=6_03_ridges.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230211_size=6_03_shading.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230211_size=6_03_valleys.PNG"/></td>
</tr>
</table>

# Area 4, center = (30, -10, 0)
This is an area with archeological features

Here's Area 4 (largest scale) on the the reference mesh: 230213_size=18_04.ply 
*The circular/bubbly 'skirt' part around the square edge of the mesh of interest is the result of screened poisson mesh reconstruction. The point cloud used for reconstruction is a square when viewed from the top!*
<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_04_max-size.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_04_top.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_04_rot_ortho.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/Area_04_rot_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">scale = 6</td>
    <td style = "text_aligh:left">scale = 9</td>
    <td style = "text_aligh:left">scale = 12</td>
    <td style = "text_aligh:left">scale = 18</td>
</tr>
<tr>
    <td style = "text_aligh:left">21421 points</td>
    <td style = "text_aligh:left">52403 points</td>
    <td style = "text_aligh:left">99264 points</td>
    <td style = "text_aligh:left">241240 points</td>
</tr>
<tr>
    <td style = "text_aligh:left">miniCrop_(30,-10,0)_scale=6.ply</td>
    <td style = "text_aligh:left">miniCrop_(30,-10,0)_scale=9.ply</td>
    <td style = "text_aligh:left">miniCrop_(30,-10,0)_scale=12.ply</td>
    <td style = "text_aligh:left">miniCrop_(30,-10,0)_scale=18.ply</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=6_04_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=9_04_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=12_04_K1.png"/></td>
    <td style="width: 240px;"><img src="../ReferenceImages/230214_size=18_04_K1.png"/></td>
</table>

Exaggerated Shading for scale = 6

<table>
<tr>
    <td style = "text_aligh:left">relief</td>
    <td style = "text_aligh:left">ridges</td>
    <td style = "text_aligh:left">shading</td>
    <td style = "text_aligh:left">valleys</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230213/230213_size=6_04_reliefs.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230213_size=6_04_ridges.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230213_size=6_04_shading.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230213_size=6_04_valleys.PNG"/></td>
</tr>
</table>

Crest Lines for scale = 16
(the three coordinates refer to the rough position of the three parameters for crest line display, top to bottom)
<table>
<tr>
    <td style = "text_aligh:left">default setting</td>
    <td style = "text_aligh:left">0, 0.75, 0</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../230213/230213_size=18_04_curves_default.PNG"/></td>
    <td style="width: 240px;"><img src="../230213/230213_size=18_04_curves_(0,.75,0).PNG"/></td>
</tr>
</table>

For Areas 5 to 11, I vary the curvature scale for an area of fixed crop size
<br>In Meshlab, use Filters->Color Creation and Processing->Colorize by Curvature (APSS)
<br>My curvature display settings are all default, **except**: 
<br>1) MLS scaling: I vary this value from 2 (default value) to 14 in incremental steps of 2
<br>2) Curvature type: K1 <- This gives the most useful kind of colorizations, which are continuous outlines

# Area 5, center = (0, -24, 0)
This is an area with archeological features
>In this area, we have an 'L' shaped and a 'C' shaped remain.
>The colorization captures these features 

<br>Scale = 24
<br>PointCloud with 1181036 points. 
<br>Point Cloud file: miniCrop_(0,-24,0)_scale=24
<br>Mesh file: 230216_size=24_05.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area5_230216/Area5_K1_MLS=14.png"/></td>
</tr>
</table>

# Area 6, center = (24, -32, 0)
This is an area with archaelogical features
>In this area, we can see some rectangles laid out neatly next to each other
><br>The colorization shows this quite well, with complete outlines

<br>Scale = 24
<br>PointCloud with 616408 points.
<br>Point Cloud file: miniCrop_(24,-32,0)_scale=24
<br>Mesh file: 230216_size=24_06.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area6_230216/Area6_K1_MLS=14.png"/></td>
</tr>
</table>

# Area 7, center = (28, 0, 0)
This is an area with archaeological features
>Clearly, there are some digging going on at the lower-right part of this crop
><br>However, the colorizaiton does not reflect this, and highlights the top left, which (I believe) are some trees

<br>Scale = 24
<br>PointCloud with 412695 points.
<br>Point Cloud file: miniCrop_(28,0,0)_scale=24.ply
<br>Mesh file: 230216_size=24_07.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area7_230216/Area7_K1_MLS=14.png"/></td>
</tr>
</table>

# **Part 2 Meshes:**
Center: (-200,-130,0)
File: part2_Mesh_inv.ply
<br><img src="../ReferenceImages/part2.png" style="width: 400px">
<br>Mesh from 230209. scale=150, poisson path=8
<br>Features in this area are **shallow**
<br>With these settings, we see contour-like (in yellow) lines everywhere. 
<br>From Area 1 Conclusions, we can say these are likely grid-based artefacts

# Area 8, center = (-210, -88, 0)
This is an area with archaeological features
>At the bottom of this area, we have the **top right** corner of a rectangular mound.
>The colorization picks out the right-angle corner, but the outline seems to blend in with the rest of the terrain, even though it is quite obvious in the shaded mesh

Scale = 24
<br>PointCloud with 307823 points.
<br>Point Cloud file: miniCrop_(-210,-88,0)_scale=24.ply
<br>Mesh file: 230216_size=24_08.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area8_230216/Area8_K1_MLS=14.png"/></td>
</tr>
</table>

# Area 9, center = (-160, -110, 0)
This is an area with archaeological feature
>In this area, we can see some shallow holes.
><br>However, only part of the holes' perimeter is highlighted in the colorization

Scale = 24
<br>PointCloud with 110585 points.
<br>Point Cloud file: miniCrop_(-160,-100,0)_scale=24.ply
<br>Mesh file: 230216_size=24_09.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area9_230216/Area9_K1_MLS=14.png"/></td>
</tr>
</table>

# **Part 3 Meshes:**
Center: (300,-50,0)

# Area 10, center = (310,-30,0)
This is an area with archaeological features
>In the **top left** of this area, we have the **bottom right** of a rectangular plateau.
><br>We also have a couple of little holes, which are from tree-planting, not archaeology
><br>It seems the colorization fails to identify the bottom right of the rectangular plateau, but highlights the tree-planting holes

<br>Scale = 24
<br>PointCloud with 33074 points.
<br>Point Cloud file: miniCrop_(310,-30,0)_scale=24.ply
<br>Mesh file: 230216_size=24_10.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area10_230216/Area10_K1_MLS=14.png"/></td>
</tr>
</table>

# Area 11, center = (280, -6, 0)
This is an area with archaeological features
>In this area, we can see there is a step-down along the tree-planting holes (we can see it from the colorization for the entirety of Part 3)
><br>However, the colorization does not show this

<br>Scale = 24
<br>PointCloud with 59180 points.
<br>Point Cloud file: miniCrop_(280,-6,0)_scale=24.ply
<br>Mesh file: 230216_size=24_11.ply

<table>
<tr>
    <td style = "text_aligh:left">where is it?</td>
    <td style = "text_aligh:left">shaded, top view, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, orthographic</td>
    <td style = "text_aligh:left">shaded, rotated 3/4, perspective</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_where.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_shaded.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_ortho.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_psp.png"/></td>
</tr>
</table>

Poisson reconstruction, path = 8, K1 curvature display

<table>
<tr>
    <td style = "text_aligh:left">MLS Filter Scale = 2</td>
    <td style = "text_aligh:left">MLS Filter Scale = 4</td>
    <td style = "text_aligh:left">MLS Filter Scale = 6</td>
    <td style = "text_aligh:left">MLS Filter Scale = 8</td>
    <td style = "text_aligh:left">MLS Filter Scale = 10</td>
    <td style = "text_aligh:left">MLS Filter Scale = 12</td>
    <td style = "text_aligh:left">MLS Filter Scale = 14</td>
</tr>
<tr>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=2.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=4.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=6.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=8.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=10.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=12.png"/></td>
    <td style="width: 240px;"><img src="../Open3D_Test/Area11_230216/Area11_K1_MLS=14.png"/></td>
</tr>
</table>

In [66]:
# Crop method 1
# I learn from code @ https://stackoverflow.com/questions/70449880/how-to-crop-a-point-cloud-in-open3d-by-using-a-polygon-volume
# it's by: SFA
# scale factor for the size of the box
scale = 24
# location of center
x = 280
y = -6
z = 0 # for the mesh, Z direction is 'UP'
# R is an identity matrix. 3 is argument, so dimemsion of R is (3 x 3)
R = np.identity(3)
extent = np.array([1, 1, 10])*scale
center = np.array([x, y, z])
# construct Oriented BoundingBox object
vol = o3d.geometry.OrientedBoundingBox(center,R,extent) # or you can use axis aligned bounding box class
print("Bounding box:")
print(vol)
# Crop point cloud 'p1', using bounding box 'vol'
crop = cloud.crop(vol)
# check # of vtx in point cloud
print("Point cloud vtx count:")
print(crop)


Bounding box:
OrientedBoundingBox: center: (280, -6, 0), extent: 24, 24, 240)
Point cloud vtx count:
PointCloud with 59180 points.


In [67]:
# output Cropped point cloud as file
o3d.io.write_point_cloud("miniCrop_(" + str(x) + "," + str(y) + ","+ str(z) + ")_scale=" + str(scale) + ".ply", crop)

True

# Crop method 2: (not good, yet to figure out how bounding box location)

In [57]:
# CROP method 2 (not working atm, cropped result has 0 points, I think)
# I learn from code @ https://stackoverflow.com/questions/61269980/open3d-crop-pointcloud-with-polygon-volume
# it's by: Eric Wiener
# define volume manually: one cube = 4 vertices total
start_x = 0.0
start_y = 0.0
start_z = 0.0
cubeSize = 10000.0
corners = np.array(
        [[start_x,             start_y,             start_z],
        [start_x,             start_y + cubeSize,  start_z],
        [start_x + cubeSize,  start_y,             start_z],
        [start_x + cubeSize,  start_y + cubeSize,  start_z],
        [start_x,             start_y,            start_z + cubeSize],
        [start_x,             start_y + cubeSize,  start_z + cubeSize],
        [start_x + cubeSize,  start_y,             start_z + cubeSize],
        [start_x + cubeSize,  start_y + cubeSize,  start_z]])
print(corners)
# convert to type float64
box = corners.astype("float64")
# initialize SelectionPolygonVolume object
vol = o3d.visualization.SelectionPolygonVolume()
# I choose the "Y" axis. I made the max value the maximum Y of
# the polygon vertices and the min value the minimum Y of the
# polygon vertices.
vol.orthogonal_axis = "Y" # orientation for the box
vol.axis_max = np.max(box[:, 1])
vol.axis_min = np.min(box[:, 1])
# Set all the Y values to 0 (they aren't needed since we specified what they
# should be using just vol.axis_max and vol.axis_min).
box[:, 1] = 0
# Convert the np.array to a Vector3dVector
vol.bounding_polygon = o3d.utility.Vector3dVector(box)
# Crop w/ variable 'box'
p1_crop = vol.crop_point_cloud(cloud)
o3d.io.write_point_cloud("p1_crop.ply", p1_crop)

[[    0.     0.     0.]
 [    0. 10000.     0.]
 [10000.     0.     0.]
 [10000. 10000.     0.]
 [    0.     0. 10000.]
 [    0. 10000. 10000.]
 [10000.     0. 10000.]
 [10000. 10000.     0.]]
[Open3D WARNING] Write PLY failed: point cloud has 0 points.


False

# .PLY point cloud to .PLY mesh
Software used: Meshlab
<br>Method: Poisson
<br>1. Calculate Normals
<br>&emsp;Filters -> Normals, Curvatures, and Orientation -> Compute Normals for point sets
<br>2. Turn point cloud to mesh
<br>&emsp;Filters -> Remeshing, Simplification, and Reconstruction -> Surface Reconstruction: Screened Poisson (Here, I use Default values from Feb 2023)

<br>Note: I use "&emsp;" (open markdown to see what's between the quotes!) to insert Tab (here, it inserts 4x spaces, which equals 1x tab)

# Turn .PLY Mesh into .PLY2 Mesh
We need .PLY2 file to use Shin Yoshizawa (et al.)'s Crest Line code (http://www2.riken.jp/brict/Yoshizawa/Research/Crest.html)
<br>The .PLY2 file is made of 4 parts (http://www2.riken.jp/brict/Yoshizawa/Research/PLYformat/PLYformat.html)
<br>&emsp;this file format is good for: "approximation of the smooth surfaces" (quote from website)
<br>1. Line 1: # of vertices (Integer)
<br>2. Line 2: # of triangles (Integer)
<br>3. Set of vertex coordinates
<br>&emsp;1x vertex per line
<br>&emsp;Format: (Double x, Double y, Double z) <-Remove comma!
<br>4. Set of face information
<br>&emsp;face = triangle
<br>&emsp;Format: (3, Int x, Int y, Int z) <-Remove comma!
<br>&emsp;here, x, y, and z are vertex ID, which are integers

In [2]:
mesh = o3d.io.read_triangle_mesh("part1_Mesh.ply")


In [3]:
verts = np.asarray(mesh.vertices)
verts_count = len(verts)
print("Vertices: " + str(verts_count) + " Total")
print(verts)
faces = np.asarray(mesh.triangles)
faces_count = len(faces)
print("Faces(Triangles): " + str(faces_count) + " Total")
print(faces)

Vertices: 76027 Total
[[-51.52429581 -80.11437988 -24.4055233 ]
 [-52.20049667 -79.86222076 -24.4055233 ]
 [-49.86222076 -81.09666443 -24.4055233 ]
 ...
 [ 10.38796234  -3.82233429  -0.16961479]
 [ 10.80348206  -3.82233429  -0.20088959]
 [ 11.21900177  -3.82233429  -0.24428368]]
Faces(Triangles): 151765 Total
[[    0    17     1]
 [    9    19     2]
 [    2    19     0]
 ...
 [76022 76015 71673]
 [73411 76022 71673]
 [71673 71674 73411]]


In [4]:
PLY2 = 'ply2.txt'
NEWLINE = '\n'

In [15]:
arr = np.array([[1.1,2,4],[3.1,4,7]])
print(" ".join(map(str, arr[1]))) # prints out array WITHOUT brackets


3.1 4.0 7.0


In [17]:
with open(PLY2, 'w') as f:
    f.write(str(verts_count) + NEWLINE)
    f.write(str(faces_count) + NEWLINE)
    for i in range(verts_count):
        f.write(" ".join(map(str, verts[i])) + NEWLINE)
    for j in range(faces_count):
        f.write('3 ' + " ".join(map(str, faces[i])) + NEWLINE)